#!/usr/bin/env bash
# Build an OpenWrt APK package for iwand.
# Usage: build_openwrt_apk.sh <architecture> <version> <binary_path> <output_path>
#
# Requires: apk (apk-tools-static from Alpine)

set -euo pipefail

ARCHITECTURE="$1"
VERSION="$2"
BINARY_PATH="$3"
OUTPUT_PATH="$4"

if [ -z "$ARCHITECTURE" ] || [ -z "$VERSION" ] || [ -z "$BINARY_PATH" ] || [ -z "$OUTPUT_PATH" ]; then
  echo "Usage: $0 <architecture> <version> <binary_path> <output_path>"
  exit 1
fi

PROJECT=$(cd "$(dirname "$0")/../.."; pwd)

# Convert version to APK format. APK only allows specific suffixes:
#   _alpha, _beta, _pre, _rc, _p (plus _cvs, _svn, _git, _hg)
# Examples:
#   0.0.0-dev       -> 0.0.0_pre0-r0
#   1.13.0-beta.8   -> 1.13.0_beta8-r0
#   1.13.0-rc.3     -> 1.13.0_rc3-r0
#   1.13.0          -> 1.13.0-r0
APK_VERSION="${VERSION#v}"
# Handle suffixes like -beta.8, -rc.3 (with dot+number)
APK_VERSION=$(echo "$APK_VERSION" | sed -E 's/-([a-z]+)\.([0-9]+)/_\1\2/')
# Map -dev to _pre0 (APK doesn't recognize _dev)
APK_VERSION=$(echo "$APK_VERSION" | sed -E 's/-dev$/_pre0/')
# Handle other simple suffixes like -alpha, -beta, -rc (without number)
APK_VERSION=$(echo "$APK_VERSION" | sed -E 's/-(alpha|beta|pre|rc)$/_\10/')
APK_VERSION="${APK_VERSION}-r0"

# apk mkpkg resolves owner/group through --root/etc/{passwd,group}
APK_ROOT_DIR=$(mktemp -d)
mkdir -p "$APK_ROOT_DIR/etc"
cat > "$APK_ROOT_DIR/etc/passwd" <<EOF
root:x:$(id -u):$(id -g):root:/root:/sbin/nologin
EOF
cat > "$APK_ROOT_DIR/etc/group" <<EOF
root:x:$(id -g):root
EOF

ROOT_DIR=$(mktemp -d)
trap 'rm -rf "$ROOT_DIR" "$APK_ROOT_DIR"' EXIT

# Binary
install -Dm755 "$BINARY_PATH" "$ROOT_DIR/usr/sbin/iwand"

# Init script (UCI-aware)
install -Dm755 "$PROJECT/luci-app-iwand/root/etc/init.d/iwand" "$ROOT_DIR/etc/init.d/iwand"

# Config files (UCI only — runtime INI generated by init script)
install -Dm600 "$PROJECT/luci-app-iwand/root/etc/config/iwand" "$ROOT_DIR/etc/config/iwand"

# LuCI files
install -Dm644 "$PROJECT/luci-app-iwand/htdocs/luci-static/resources/view/iwand.js" \
  "$ROOT_DIR/www/luci-static/resources/view/iwand.js"
install -Dm644 "$PROJECT/luci-app-iwand/root/usr/share/luci/menu.d/luci-app-iwand.json" \
  "$ROOT_DIR/usr/share/luci/menu.d/luci-app-iwand.json"
install -Dm644 "$PROJECT/luci-app-iwand/root/usr/share/rpcd/acl.d/luci-app-iwand.json" \
  "$ROOT_DIR/usr/share/rpcd/acl.d/luci-app-iwand.json"

# APK metadata directory
PACKAGES_DIR="$ROOT_DIR/lib/apk/packages"
mkdir -p "$PACKAGES_DIR"

# conffiles
cat > "$PACKAGES_DIR/.conffiles" <<'CONFFILES'
/etc/config/iwand
CONFFILES

# conffiles_static (sha256 checksums of default config)
while IFS= read -r conffile; do
  sha256=$(sha256sum "$ROOT_DIR$conffile" | cut -d' ' -f1)
  echo "$conffile $sha256"
done < "$PACKAGES_DIR/.conffiles" > "$PACKAGES_DIR/.conffiles_static"

# file list (excluding metadata)
(cd "$ROOT_DIR" && find . -type f -o -type l) \
  | sed 's|^\./|/|' \
  | grep -v '^/lib/apk/packages/' \
  | sort > "$PACKAGES_DIR/.list"

# Post-install script: enable service for procd trigger support
POSTINST=$(mktemp)
cat > "$POSTINST" << 'POSTEOF'
#!/bin/sh
[ -x /etc/init.d/iwand ] && /etc/init.d/iwand enable 2>/dev/null
exit 0
POSTEOF
chmod 755 "$POSTINST"

# Pre-deinstall script: stop and disable service
PRERM=$(mktemp)
cat > "$PRERM" << 'PRERMEOF'
#!/bin/sh
/etc/init.d/iwand stop 2>/dev/null
/etc/init.d/iwand disable 2>/dev/null
rm -f /etc/rc.d/S99iwand /etc/rc.d/K10iwand 2>/dev/null
exit 0
PRERMEOF
chmod 755 "$PRERM"

# Build APK
apk --root "$APK_ROOT_DIR" mkpkg \
  --info "name:iwand" \
  --info "version:${APK_VERSION}" \
  --info "description:Panabit iWAN SD-WAN client daemon" \
  --info "arch:${ARCHITECTURE}" \
  --info "license:MIT" \
  --info "origin:iwand" \
  --info "url:https://github.com/Ricky-Hao/iwand" \
  --info "maintainer:Ricky-Hao <14084342+Ricky-Hao@users.noreply.github.com>" \
  --info "depends:kmod-tun" \
  --info "provider-priority:100" \
  --script "post-install:${POSTINST}" \
  --script "pre-deinstall:${PRERM}" \
  --files "$ROOT_DIR" \
  --output "$OUTPUT_PATH"

rm -f "$POSTINST" "$PRERM"

echo "Built APK: $OUTPUT_PATH (arch: $ARCHITECTURE, version: $APK_VERSION)"
